set(_CATKIN_CURRENT_PACKAGE "robotics-studio-1")
set(robotics-studio-1_VERSION "0.0.1")
set(robotics-studio-1_MAINTAINER "Pawarat Phatthanaphusakun <Pawarat.phatthanaphusakun-1@student.uts.edu.au>")
set(robotics-studio-1_PACKAGE_FORMAT "1")
set(robotics-studio-1_BUILD_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "nav_msgs" "rosbag" "roslib")
set(robotics-studio-1_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "nav_msgs" "rosbag" "roslib" "message_runtime")
set(robotics-studio-1_BUILDTOOL_DEPENDS "catkin")
set(robotics-studio-1_BUILDTOOL_EXPORT_DEPENDS )
set(robotics-studio-1_EXEC_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "nav_msgs" "rosbag" "roslib" "message_runtime")
set(robotics-studio-1_RUN_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "nav_msgs" "rosbag" "roslib" "message_runtime")
set(robotics-studio-1_TEST_DEPENDS )
set(robotics-studio-1_DOC_DEPENDS )
set(robotics-studio-1_URL_WEBSITE "")
set(robotics-studio-1_URL_BUGTRACKER "")
set(robotics-studio-1_URL_REPOSITORY "")
set(robotics-studio-1_DEPRECATED "")